name: camera_kit_manager
description: An app for camera assistants to track rental equipment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  share_plus: ^10.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0  
  # win32: 5.0.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true